<testsuite errors="0" failures="3" name="unittest.suite.TestSuite" tests="6" time="0.020">
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_001_t" time="0.0036"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_002_t" time="0.0023">
    <failure type="exceptions.AssertionError">Tuples differ: (0, 0, 0, 0, 1, 3, 2, 4) != (0, 0, 0, 0, 0, 0, 0, 0)

First differing element 4:
1
0

- (0, 0, 0, 0, 1, 3, 2, 4)
?              ^  ^  ^  ^

+ (0, 0, 0, 0, 0, 0, 0, 0)
?              ^  ^  ^  ^

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/ubuntu/tcc/gnuradio/gr-tcc_sdr/python/qa_interleaver_bb.py", line 56, in test_002_t
    self.assertEqual(expected_result, result_data)
  File "/usr/lib/python2.7/unittest/case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 751, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 722, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 408, in fail
    raise self.failureException(msg)
    </failure>
  </testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_003_t" time="0.0026">
    <failure type="exceptions.AssertionError">Tuples differ: (0, 0, 0, 0, 0, 0, 1, 4, 2, 5,... != (0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...

First differing element 6:
1
0

- (0, 0, 0, 0, 0, 0, 1, 4, 2, 5, 3, 6)
?                    ^  ^  ^  ^  ^  ^

+ (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
?                    ^  ^  ^  ^  ^  ^

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/ubuntu/tcc/gnuradio/gr-tcc_sdr/python/qa_interleaver_bb.py", line 68, in test_003_t
    self.assertEqual(expected_result, result_data)
  File "/usr/lib/python2.7/unittest/case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 751, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 722, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 408, in fail
    raise self.failureException(msg)
    </failure>
  </testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_004_t" time="0.0054">
    <failure type="exceptions.AssertionError">Tuples differ: (0, 0, 0, 0, 0, 0, 0, 0, 0, 1,... != (0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...

First differing element 9:
1
0

- (0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0)
?                             ---------

+ (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
?                                            +++++++++

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/ubuntu/tcc/gnuradio/gr-tcc_sdr/python/qa_interleaver_bb.py", line 80, in test_004_t
    self.assertEqual(expected_result, result_data)
  File "/usr/lib/python2.7/unittest/case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 751, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 722, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 408, in fail
    raise self.failureException(msg)
    </failure>
  </testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_005_t" time="0.0033"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_006_t" time="0.0021"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
